[package]
name = "chip8sys"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.28"
rand = "0.9.2"
rodio = "0.21.1"

[lib]
name = "chip8sys"
path = "src/lib.rs"

[[bin]]
name = "chip8sys"
path = "src/main.rs"
