[package]
name = "chip8sys"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "*"

# random
getrandom = { version = "0.3.3", default-features = false, features = ["wasm_js"] }

[lib]
name = "chip8sys"
path = "src/lib.rs"
